server:
  port: 5555
  
spring:
  application:
    name: withdrawservice
    
eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://microservices-eureka-service:8761/eureka/
  instance:
     hostname: withdrawservice
  